name: Docker Build, ECR Push, and ECS Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: ${{ secrets.AWS_REGISTRY }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build Docker image
        run: docker build -t your-image-name .

      - name: Tag Docker image
        run: docker tag your-image-name:latest ${{ steps.login-ecr.outputs.registry }}:latest

      - name: Push Docker image to Amazon ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}:latest

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Login to Amazon ECS
        uses: aws-actions/amazon-ecs-login@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1

      - name: Deploy to Amazon ECS
        run: |
          aws ecs update-service \
            --cluster your-cluster \
            --service your-service \
            --force-new-deployment \
            --region your-region
